AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Actions Service Stack


Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  FunctionName:
    ActionFunction:
      test: test-actions
      stage: stage-actions
      prod: prod-actions
    ActionFunctionTargetGroup:
      test: test-actions-tg
      stage: stage-actions-tg
      prod: prod-actions-tg

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            DELIVERY_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, DeliveryStreamExportName] ]
            INTERNAL_AUTH_FUNCTION_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalGetUserIdFunctionExport] ]
            COMMON_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExportName] ]
        Tags:
          Company: Ringoid
          Service: actions
          Environment: !Ref Env

Resources:

  ActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, ActionFunction, !Ref Env]
      Handler: actions
      CodeUri: ./actions.zip
      Description: Actions function
      Policies:
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonKinesisFullAccess

  ActionTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, ActionFunctionTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt ActionFunction.Arn
      TargetLambdaFunctionName: !Ref ActionFunction

  ActionListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt ActionTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/actions/actions"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 301
